# @package _global_
benchmark: 
  _target_: dacbench.benchmarks.SigmoidBenchmark
  config:
    instance_set_path: ../instance_sets/sigmoid/sigmoid_2D3M_train.csv
    test_set_path: ../instance_sets/sigmoid/sigmoid_2D3M_test.csv

instance_set_id: 2D3M_train
benchmark_id: Sigmoid
num_episodes: 1000