# @package _global_
agent_name: random
agent:
  _target_: dacbench.agents.simple_agents.RandomAgent
  _partial_: True

outdir: runs/${benchmark_id}
hydra:
  run:
    dir: runs/${benchmark_id}/${test_set_id}/${agent_name}/${instance_set_selection}/${seed}  # /${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${outdir}  # /${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${test_set_id}/${agent_name}/${instance_set_selection}/${seed}
