# @package _global_
agent_name: sac_sb3
agent:
  _target_: instance_dac.agents.sb3.SB3Agent
  _partial_: True
  agent:
    _target_: stable_baselines3.sac.SAC
    _partial_: True
    policy: MlpPolicy
    seed: ${seed}
    verbose: 0
  
