# @package _global_

instance_set_id: seplow_train_0.1_411
instance_set_selection: random
selector:
  seed: 411
  fraction: 0.1
source_instance_set_id: seplow_train
benchmark:
  config:
    instance_set:
      4:
      - 10
      - 2
      - 0
      - - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
      7:
      - 10
      - 2
      - 3
      - - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
      36:
      - 10
      - 10
      - 0
      - - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
      6:
      - 10
      - 2
      - 2
      - - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
    instance_set_path: null
    test_set_path: ../../../instance_dac/instance_sets/cmaes/seplow/test.csv
hydra:
  run:
    dir: runs/${benchmark_id}/${source_instance_set_id}/${agent_name}/${instance_set_selection}/${instance_set_id}/${seed}
  sweep:
    dir: runs/${benchmark_id}
    subdir: ${source_instance_set_id}/${agent_name}/${instance_set_selection}/${instance_set_id}/${seed}
