# @package _global_

instance_set_id: seplow_train_0.1_234235
instance_set_selection: random
selector:
  seed: 234235
  fraction: 0.1
source_instance_set_id: seplow_train
benchmark:
  config:
    instance_set:
      38:
      - 10
      - 10
      - 2
      - - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
      24:
      - 10
      - 7
      - 0
      - - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
      2:
      - 10
      - 1
      - 2
      - - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
      26:
      - 10
      - 7
      - 2
      - - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
    instance_set_path: null
    test_set_path: ../../../instance_dac/instance_sets/cmaes/seplow/test.csv
hydra:
  run:
    dir: runs/${benchmark_id}/${source_instance_set_id}/${agent_name}/${instance_set_selection}/${instance_set_id}/${seed}
  sweep:
    dir: runs/${benchmark_id}
    subdir: ${source_instance_set_id}/${agent_name}/${instance_set_selection}/${instance_set_id}/${seed}
