# @package _global_

instance_set_id: seplow_train_0.1_32544
instance_set_selection: random
selector:
  seed: 32544
  fraction: 0.1
source_instance_set_id: seplow_train
benchmark:
  config:
    instance_set:
      28:
      - 10
      - 8
      - 0
      - - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
      9:
      - 10
      - 3
      - 1
      - - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
      12:
      - 10
      - 4
      - 0
      - - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
      23:
      - 10
      - 6
      - 3
      - - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
    instance_set_path: null
    test_set_path: ../../../instance_dac/instance_sets/cmaes/seplow/test.csv
hydra:
  run:
    dir: runs/${benchmark_id}/${source_instance_set_id}/${agent_name}/${instance_set_selection}/${instance_set_id}/${seed}
  sweep:
    dir: runs/${benchmark_id}
    subdir: ${source_instance_set_id}/${agent_name}/${instance_set_selection}/${instance_set_id}/${seed}
