defaults:
  - _self_
  - agent: ppo
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog



seed: 1
benchmark: 
  # Seed is the same for each benchmark
  # For the _target_ and other config args set in configs/benchmark/...
  config:
    seed: ${seed}
    instance_set_path: ???  # set in instance
    test_set_path: ???  # set in instance
benchmark_id: ???  # set in benchmark/...
instance_set_id: ???  # set in benchmark/...
num_episodes: ???  # set in benchmark/...
instance_set_selection: full

evaluate: False
eval_on_train_set: False
num_eval_episodes: 10  # per instance

log_only_performance: False  # TODO Check if we need all logs: Relevant for evaluating oracle? 



outdir: runs/${benchmark_id}
hydra:
  run:
    dir: runs/${benchmark_id}/${instance_set_id}/${instance_set_selection}/${seed}  # /${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${outdir}  # /${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${instance_set_id}/${instance_set_selection}/${seed}